//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abc.Mvc.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Abc.Mvc.WebUI.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string ab {
            get {
                return ResourceManager.GetString("ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Açıklaması.
        /// </summary>
        public static string ab1 {
            get {
                return ResourceManager.GetString("ab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Fiyati.
        /// </summary>
        public static string ab2 {
            get {
                return ResourceManager.GetString("ab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Stok Adedi.
        /// </summary>
        public static string ab3 {
            get {
                return ResourceManager.GetString("ab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Görselleri.
        /// </summary>
        public static string ab4 {
            get {
                return ResourceManager.GetString("ab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Anasayfada.
        /// </summary>
        public static string ab5 {
            get {
                return ResourceManager.GetString("ab5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Stokta.
        /// </summary>
        public static string ab6 {
            get {
                return ResourceManager.GetString("ab6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string ab7 {
            get {
                return ResourceManager.GetString("ab7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string acıklama {
            get {
                return ResourceManager.GetString("acıklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adet.
        /// </summary>
        public static string adet {
            get {
                return ResourceManager.GetString("adet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Sepeti.
        /// </summary>
        public static string alisveris {
            get {
                return ResourceManager.GetString("alisveris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara Toplam.
        /// </summary>
        public static string ara {
            get {
                return ResourceManager.GetString("ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string detay {
            get {
                return ResourceManager.GetString("detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string duzenle {
            get {
                return ResourceManager.GetString("duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string evet {
            get {
                return ResourceManager.GetString("evet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string fiyat {
            get {
                return ResourceManager.GetString("fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string giris {
            get {
                return ResourceManager.GetString("giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string giris1 {
            get {
                return ResourceManager.GetString("giris1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string guncelle {
            get {
                return ResourceManager.GetString("guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string hayır {
            get {
                return ResourceManager.GetString("hayır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kategoriler.
        /// </summary>
        public static string kategori1 {
            get {
                return ResourceManager.GetString("kategori1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamera.
        /// </summary>
        public static string kategori2 {
            get {
                return ResourceManager.GetString("kategori2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgisayar.
        /// </summary>
        public static string kategori3 {
            get {
                return ResourceManager.GetString("kategori3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronik.
        /// </summary>
        public static string kategori4 {
            get {
                return ResourceManager.GetString("kategori4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string kategori5 {
            get {
                return ResourceManager.GetString("kategori5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori.
        /// </summary>
        public static string kategori7 {
            get {
                return ResourceManager.GetString("kategori7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Listesi.
        /// </summary>
        public static string kategori8 {
            get {
                return ResourceManager.GetString("kategori8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı.
        /// </summary>
        public static string kategori9 {
            get {
                return ResourceManager.GetString("kategori9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string kategorii {
            get {
                return ResourceManager.GetString("kategorii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string kayit {
            get {
                return ResourceManager.GetString("kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string kullanıcı {
            get {
                return ResourceManager.GetString("kullanıcı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string kullanıcı2 {
            get {
                return ResourceManager.GetString("kullanıcı2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kullanıcı.
        /// </summary>
        public static string kullanici5 {
            get {
                return ResourceManager.GetString("kullanici5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Oluştur.
        /// </summary>
        public static string kullanıcı6 {
            get {
                return ResourceManager.GetString("kullanıcı6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeye Geri Dön.
        /// </summary>
        public static string liste {
            get {
                return ResourceManager.GetString("liste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string navbar1 {
            get {
                return ResourceManager.GetString("navbar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string navbar2 {
            get {
                return ResourceManager.GetString("navbar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim Paneli.
        /// </summary>
        public static string navbar3 {
            get {
                return ResourceManager.GetString("navbar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Seçenekleri.
        /// </summary>
        public static string odeme {
            get {
                return ResourceManager.GetString("odeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellik.
        /// </summary>
        public static string ozellik {
            get {
                return ResourceManager.GetString("ozellik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete Ekle.
        /// </summary>
        public static string sepet {
            get {
                return ResourceManager.GetString("sepet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stokta.
        /// </summary>
        public static string stok {
            get {
                return ResourceManager.GetString("stok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stokta Yok.
        /// </summary>
        public static string stok2 {
            get {
                return ResourceManager.GetString("stok2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü İncele.
        /// </summary>
        public static string urun {
            get {
                return ResourceManager.GetString("urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürün.
        /// </summary>
        public static string urun3 {
            get {
                return ResourceManager.GetString("urun3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Listesi.
        /// </summary>
        public static string urun4 {
            get {
                return ResourceManager.GetString("urun4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string urun5 {
            get {
                return ResourceManager.GetString("urun5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Yap.
        /// </summary>
        public static string yorum1 {
            get {
                return ResourceManager.GetString("yorum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string yorum2 {
            get {
                return ResourceManager.GetString("yorum2", resourceCulture);
            }
        }
    }
}
